name: ai_chat_plus
description: "🌟 A cutting-edge Flutter chat experience with seamless AI integration. Features real-time interactions, and intelligent responses powered by OpenAI, Gemini, and Claude. Crafted with precision by Jamalihassan0307."
version: 1.1.6
homepage: https://github.com/jamalihassan0307/ai_chat_plus
repository: https://github.com/jamalihassan0307/ai_chat_plus

environment:
  sdk: ">=3.0.0 <4.0.0"  # Relaxed SDK constraint
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # AI Model Integration
  dart_openai: ^5.1.0
  google_generative_ai: ^0.4.6
  http: ^1.3.0
  json_annotation: ^4.9.0
  universal_io: ^2.2.2  # Platform-agnostic IO operations
  web_socket_channel: ^2.4.0  # Keeping at 2.4.0 for compatibility

  # State Management
  provider: ^6.1.4

  # Data Models & Serialization
  freezed_annotation: ^2.4.1  # Keeping at 2.4.1 for SDK compatibility
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7  # Keeping at 2.4.7 for SDK compatibility

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:
#   plugin:
#     platforms:
#       android:
#         package: com.example.ai_chat_plus
#         pluginClass: AIChatPlusPlugin
#       ios:
#         pluginClass: AIChatPlusPlugin
#       web:
#         pluginClass: AIChatPlusWeb
#         fileName: ai_chat_plus_web.dart
     

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
